### PR TITLE
Highlight farthest coinciding ancestor

### PR DESCRIPTION
**Pull request by ccjmne**
This PR proposes to implement the selection of the outermost ancestor to the jump node that:
- is valid
- shares starting coordinates with the jump node

This implementation only bothers with computing the "ideally" selected node when highlighting is activated.

Here's a screencast of the fixed behaviour in action:
[asciicast](https://asciinema.org/a/ttigJi4EmqKkGZ23gw7DDJZKS)

This fixes https://github.com/aaronik/treewalker.nvim/issues/8.

### CODE REVIEW

**Comment by aaronik** [comment]
Mmm I'm working on this on my end as well. 

There's an issue with this though, which is the same issue that makes this plugin any difficulty to develop at all. And that's this -- you don't actually know what node you're on. nvim's treesitter chose to select the smallest node, this selects the biggest node. But the real issue is, it can be any node including those two or in between.

It's hard to see what's going on in your video, but I have your branch and am trying it out (it's virtually the same implementation as I have locally), and it has the same problem as mine. In the acceptance_spec file you're using as an example, when you land on load_buf, the entire body of the function is highlighted. This is wrong behavior.

I'm racking my brain trying to figure out a way to get the "right" node, but I haven't come up with anything yet. If this can be solved, then node swapping can also be solved, which would be radical. But finding the highest ancestor with same start point is not the solution.

To further exemplify why, try the ruby file included in the repo. When you jump from the second class up to the first, it highlights the whole file, because the highest node with the same start point as the line at the top of the file is the whole module, so it selects the whole module.

**Comment by ccjmne** [comment]
Thanks for checking it out!

I think I've managed to come up with an extraordinarily simple solution: have a blacklist of nodes that are never the right ones to highlight.
It's possible that it may require some per-language curation, but if this is the way to go, I'm sure it wouldn't be a problem in the future.

The only curiosity remaining is that... extraordinarily simple solutions may be subtly wrong in many ways :)

In any case, this works splendidly with the Ruby fixture you were pointing to.

--

Regarding nodes selection... yeah, I know that it's another topic altogether, that we'll have to figure out later as well anyways, if we want to start swapping things around... But this PR I introduced actually only changes the node that is *highlighted*, so it should be able to work without even us introducing a notion of "currently selected node".

Let me know what you think!

**Comment by ccjmne** [comment]
Hm, I edited my previous comment, which was a bit misguided ;)
If you'd like to chat about what the challenges are, regarding the node selection—or give me some pointers to other resources to read, please don't hesitate to reach out: I feel like I'm not seeing the full picture.
Thanks again!

**Comment by aaronik** [comment]
Yeah the blacklist is also something that I tried when originally implementing this. And the thing you identified is the reason I didn't want to go with it - it requires a custom list for every language. Just trying to get the languages I use on the regular to work was already turning into a massive headache - the list was growing longer and longer by the minute, and eventually some node types started to conflict - wanting them in for some languages and not others. Of course we could start checking for filetype extensions, but.... I really, really don't want to do that. The plugin gets way more cumbersome and complex, and way less useful, once we need to start maintaining lists like that.

There's got to be a more elegant solution out there. I'm going to keep thinking on it, and let me know if you come up with anything too.

I really appreciate your participation on this! This particular issue is by far the most important issue in this plugin.

EDIT: Ah yeah I see there're still remnants of my attempts with the descendant whitelist. That's a vestige, currently unused. But definitely misleading. I'm cleaning that up now.

**Comment by aaronik** [comment]
The first iteration of this plugin was the original naive version probably everyone thinks of:

Up/Down jump to neighbor nodes, Left goes to parent node, and Right goes to first child.

Of those, Left is close. But as far as neighboring nodes, forget it, half the languages have ASTs that just don't work like that. Same with first child, noting that a design goal for this plugin is statelessness, so there are two sides to a node - identifying which node is your next jump target, and _getting the current node_. If you jump to the former, when you get the latter, it'll **likely** be a different node, which leads to getting "stuck" a lot.

So for the second iteration I implemented what I thought was a clever idea: **remake the entire tree, such that there's only ever one node per line**. I got a prototype working, but it was slow, and my OS started telling me the terminal emulator was using a lot of power, lol.

Onto the third and final iteration - I realized what I was looking for in this plugin was movement around _how I'm viewing the code_, for which I was making ASTs a proxy. But they're only a proxy, actually. It's actually line based movement that I'm looking for, where line number and indentation are the important pieces of semantic information. It felt a little dirty, kind of cheating, and definitely wasn't going to work on minified files, ([or markdown, apparently](https://github.com/aaronik/treewalker.nvim/issues/2)), etc. But it was the only way to make the thing work. And now it works great, so that's what I stuck with.

But the problem of node selection never got solved, it just got swept under the rug. And it's precisely because **most of the time** we want the highest node on the line, but **sometimes** we don't. We don't when the node is called "body", or "block", or "body_block", or "block_statement", or "program", or "module", or "chunk", or one of probably a thousand other types.

**Comment by aaronik** [comment]
Let me sleep on this one. Maybe, even if it's broken sometimes after this change, it'll still be fixed for more times. Rust and Javascript would still have issues if we tried to utilize this blacklist in target finding, because of how they setup their trees. But maybe using this in tandem with the raw linenumber/indent approach would yield good results.

**Comment by ccjmne** [comment]
Thank you for these explanations.

Hahaha, yep, I did think the current (/third/final) iteration was a bit surprising: "why not just _do the thing_?"...
Then I opened the AST and realised, just as you did, that I'm not actually looking for a way to browse _that_ and that "_doing the thing_" I was naively alluding to in my head wouldn't at all be practical.

I think maybe there's some sort of a solution that may vaguely work out, but would probably need to be tinkered with before I realise it's utter nonsense. I'll sleep on it as well and see whether I can get something brewing in the background. If something starts looking like it's getting somewhere, I'll be sure to let you know :)

Cheers!

**Comment by aaronik** [comment]
Alright I've thought about this and have concluded it's a definite improvement :)

I'm going to pull this into a branch, rebase it and integrate it with the existing changes, then attempt a regex based system, similar to the existing jump blacklist -- maybe this is a world where a handful of entries there will catch most languages 🤞 .

Thanks again for your help, @ccjmne! I very much welcome all of your contributions 😃🙏❤️

**Pull request merged**
