### PR TITLE
Add swap next and swap previous node

### PR DESCRIPTION
**Pull request by duqcyxwd**
Nice plugin! The code is well-organized. 

I've had similar code in my dot file for a while, but I haven't had time to refactor it into a plugin. So, I think it would be better to contribute to yours instead of writing my own.

My solution is based on a concept called the **current top node**. I use the topmost node starting at my current cursor as the starting point. This allows me to easily navigate to the next Tree-sitter neighbour by calling "next_named_sibling()" on the current top node. It also lets me swap the node using Tree-sitter utility functions.

This can help to solve the issue https://github.com/aaronik/treewalker.nvim/issues/4

Demo:
[asciicast](https://asciinema.org/a/PhpuZLywiF3HSHGLAZ35PEFvu)

I think there might be various strategies for navigating the Tree-sitter node tree beyond yours and mine. It would be wonderful to give users the option to configure it based on their preferences.

### CODE REVIEW

**Comment by aaronik** [comment]
Hey man this is amazing, thank you for opening a PR to add these to the plugin! 

I think this is the right idea. It's funny, we all seem to be having this same insight about the "top node", or "highest ancestor on same row", or "highest coincident". And this is true most of the time -- I see you added "body" to the jump target blacklist - that list ends up being the sticking point. See [nodes.lua](https://github.com/aaronik/treewalker.nvim/blob/main/lua/treewalker/nodes.lua#L9) for the current iteration of that list, and [this comment](https://github.com/aaronik/treewalker.nvim/pull/9#issuecomment-2544218790) and its surrounding thread for more of my ranting about it.

Ultimately I think the two lists will get folded into one, like you have here, and then I'll bring in your changes here.

But before they go live, there is one bit that I feel needs to be added for this to really be ready for prime time - and that's that the comments "associated" with a node need to travel with it. I suspicion that won't be too difficult, just will take some doing and some diligent testing. I did suspicion that this plugin would be easier to write though so all suspicions are suspect if you will.

Also I'd love to not add `nvim-treesitter` as a dependency - I used it for a while, but I think most of what it does can also be done with raw `vim.treesitter`. Maybe it was a precursor and now it's mostly in nvim itself? I know that happened with Plenary.

cc @ccjmne

**Comment by duqcyxwd** [comment]
Hi @aaronik I've read all your comments, and I really enjoyed the discussion!

It seems like you've put a lot of thought into this! If we're just viewing the code, we don't need to worry about the current node. Defining the current node is important only when we need to manipulate the code. I think using the topmost node with a filter list could be a workable solution for now. As you mentioned, the downside is that we might need to create a blacklist, and it could break for some languages. 

I also have this node raise based on the topmost node concept. If you'd like, I can open another GCR for it as well.
[asciicast](https://asciinema.org/a/73wKwnuvCOEnonFikg9a6USm5)


Regarding the `nvim-treesitter`, thanks for letting me know about it. I didn't realize so many functions are already integrated into Neovim! I'll switch most of my function calls to the built-in ones.

The only missing function is `ts_utils.swap_nodes`. I'm not sure if you want to rewrite this function in the plugin or, like I did, add dependencies. I'm still using `nvim-treesitter` to install other language parsers, so adding the dependency isn't a big deal for me. However, it might mean extra dependencies for those who only use Neovim's built-in Treesitter parsers. Let me know what you think 😄

**Comment by aaronik** [comment]
Closing this as implemented in [d09fbe7b10d39191ca4a62213517a758465d1b38](https://github.com/aaronik/treewalker.nvim/commit/d09fbe7b10d39191ca4a62213517a758465d1b38).

I appreciate the PR though, so I linked to it in the new readme. Thanks again @duqcyxwd!

**Comment by aaronik** [comment]
@duqcyxwd Just wanted to drop a line and let you know that the plugin now has left/right swapping built right. Please feel free to give it a shot and let me know if it's working for you or if it needs any more polish. Thanks!

**Pull request closed without merging**
