### PR TITLE
Make highlight duration configurable

### PR DESCRIPTION
**Pull request by ccjmne**
Hi,
Thank you for this excellent plug-in!

I like the highlighting, but would want it a bit snappier.

This PR answers that concern by letting `opts.highlight` be a `boolean | integer`. I don't know what you think about that; it could also be a separate property, and I'd be happy to make any changes.

The highlighting is now cleared after the duration defined by that value, or `250` by default—as you had originally set it up to be.

The table below illustrates the upgraded behaviour:

| opts.highlight  |       behaviour      |
|-----------------|----------------------|
| `nil`             |  no highlighting     |
| `false`           |  no highlighting     |
| `0`               |  no highlighting     |
| `true`            |  highlight for `250ms` |
| `n` where `n > 0`   |  highlight for `<n>ms` |

Fixes https://github.com/aaronik/treewalker.nvim/issues/5.

### CODE REVIEW

**Comment by aaronik** [comment]
So a big part of this plugin is that it's supposed to be _dead simple_. Just totally stupidly simple, nothing can mess it up. And part of that, for me, is minimal config. For plugins and the like, I'm definitely a "batteries included" kind of person. The only reason I included an option to turn highlighting off at all is that I worried not having that would cause people with epilepsy to not be able to use the plugin, and I didn't think that'd be fair.

So for this, here's what I'd like to do:

* If this does end up making it in, it'll be a different top level opts key just called `highlight_duration` or something, not combining the existing option (although it's clever the way you've implemented it so that nobody's existing config would break! I appreciate the attention to that detail.)
* I'd like to let the highlight behavior bake for a little while and see if other people are really pining for it. I think thumbs ups on the issue/PR could be a good metric for that.

I really like your tests for this, though, just to throw that out there. Really good work on those.

The vim.uv change seems really pertinent - if you want to take that out and throw it into another PR I'd be happy to merge that right away.

**Comment by ccjmne** [comment]
Thank you @aaronik!

I was already on the fence about it being a different property: in general, I like my stuff to be **dead simple** as well, so I really appreciate the sentiment.
I've actually been on a crusade in favour of radical simplicity at work lately, I really couldn't be happier with your approach!

On the other hand, I've observed that these values are regularly "adaptable" for further tweaking, like I did just here, and it does make it impossible to end up with semantically contradictory configs like `highlight = false, highlight_duration = 250` or `highlight = true, highlight_duration = 0`... Not that either would effectively be a problem anyways, only one reasonable thing could be happening in these cases.

Anyhow, reiterating for clarity: I'm not pushing back at all against your decision, I was already on the fence when I opened this PR.
And I'm happy with it sitting here a while and see whether it's something people want!

Cheers!

**Comment by ccjmne** [comment]
Oh, and I removed the reliance on `vim.loop`/`vim.uv` in the end: no need to measure anything here, just wait 'till things are expected to happen, assert that they haven't before and that they do then :)

**Comment by aaronik** [comment]
After the highlighting got better (with your help), I started to also want to make the highlighting a little more snappy :) So this is in!

The branch was quite far behind, and I didn't want the merge commits, so I got kinda hacky and individually cherry picked each of your commits in this branch (kinda like a rebase I guess). So your commits are in main. See [the contributor list](https://github.com/aaronik/treewalker.nvim/graphs/contributors).

**Comment by ccjmne** [comment]
Oh, wow, excellent!

Yeah, earlier I did mess up somewhat with the extra merge commit "in the middle"... Then, seeing as we're all working at the same time on the same files, I figured I'd bother with maintaining a *single* "rolling merge commit" with `rerere` so that the history would still look "clean enough"... But I think I'll get into the habit of always doing that from the beginning: that sounds like a good habit!
In any case, the PR needed some amendments anyway, because it was clear the `highlight_duration` should be an option on its own.

Thank you for ensuring I was still on the contributors' list!
With "tricky merges" like these (where content has changed so much and was split into different files), it's sometimes tempting to just check out both things, shuffle bits around, test it, save it, and end up losing history/attribution. I'm grateful for your care here!

**Pull request closed without merging**
